apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
  namespace: socket-talk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
      - name: db-service
        image: ashutoshsagar/db-service:latest
        envFrom:
        - secretRef:
            name: app-secrets