name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. (Optional) Debug: List directories to confirm paths
      - name: List repository structure
        run: |
          echo "Root directory:"
          ls -la
          echo "apps directory:"
          ls -la apps
          echo "http-server directory:"
          ls -la apps/http-server

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build and push http-server image
      - name: Build and push http-server image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/http-server
          file: ./apps/http-server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/http-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/http-server:${{ github.sha }}

      # 6. Build and push ws-server image
      - name: Build and push ws-server image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/ws-server
          file: ./apps/ws-server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ws-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ws-server:${{ github.sha }}

      # 7. Build and push db-service image
      - name: Build and push db-service image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/db-service
          file: ./apps/db-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/db-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/db-service:${{ github.sha }}

      # 8. Build and push frontend image
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/frontend
          file: ./apps/frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
