name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx for building images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (ensure you've added DOCKERHUB_USERNAME and DOCKERHUB_TOKEN as secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push http-server image
      - name: Build and push http-server image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/http-server
          file: ./apps/http-server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/http-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/http-server:${{ github.sha }}

      # Build and push ws-server image
      - name: Build and push ws-server image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/ws-server
          file: ./apps/ws-server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ws-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ws-server:${{ github.sha }}

      # Build and push db-service image
      - name: Build and push db-service image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/db-service
          file: ./apps/db-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/db-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/db-service:${{ github.sha }}

      # Build and push frontend image
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/frontend
          file: ./apps/frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
